name: Nested

on:
  push:
    branches:
      - master
    paths:
      - my-app/**
  workflow_dispatch:

defaults:
  run:
    working-directory: ./my-app

jobs:
  job-from-nested-job:
    steps:
      - name: nested job step
        run: >
          echo $(pwd)
