name: Nested

on:
  push:
    branches:
      - master
    paths:
      - my-app/**
  workflow_dispatch:

defaults:
  run:
    working-directory: ./my-app

jobs:
  from-nested-job:
    run: >
      echo $(pwd)
