name: Parent

on:
  push:
    branches:
      - master
    paths:
      - my-app/**
  workflow_dispatch:

defaults:
  run:
    working-directory: ./my-app

jobs:
  parent-job:
    runs-on:
      ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: parent job step
        run: >
          echo $(pwd)

      - name: nested job step
        uses: .github/workflows/nested.yaml
