name: Parent

on:
  push:
    branches:
      - master
    paths:
      - my-app/**
  workflow_dispatch:

defaults:
  run:
    working-directory: ./my-app

jobs:
  parent-job:
    steps:
      - name: parent job step
        run: >
          echo $(pwd)

      - name: nested job step
        uses: ./.github/workflows/nested.yaml
